### ISSUE TITLE
Design Firecamp Desktop App Download Page

### ISSUE THREAD

**Issue by shreya-gr** [firecamp-dev/website#18]
**User Story**
As a user, I want to be able to easily download the Firecamp desktop app so I can start using it on my computer.

**App** : Production and Canary 
**Platform** : Mac, Windows, Ubuntu 

**Tasks**
 Design a new page on the Firecamp website for downloading the desktop app

- [ ] Clear download button/link
- [ ] Download buttton will be set based on the system. ie, for Mac it should be mac download link.  
- [ ] Short instructions for installing the app

**Content**: 
Hero : Download Firecamp 
Sub Hero : Start building APIs 3x faster with your team

CTA : Download Firecamp for Mac/Windows/ Ubuntu 

Privacy policy : By downloading and using Firecamp, I agree to the [Privacy Policy](https://firecamp.io/legal/privacy-policy) and [Terms](https://firecamp.io/legal/terms-and-conditions).

_To design this page feel free to take inspiration from any great product's download page._

**Comment by shreya-gr** [comment]
@Kritik-J would you be interested in working on this issue?

**Comment by Kritik-J** [comment]
Yes, Please assign this to me

**Comment by shreya-gr** [comment]
@Kritik-J have great thanks. Assigned to you, please prepare mockup and share here.  
Looking forward to new download page.

**Comment by rohitmondal03** [comment]
Hey @shreya-gr is this issue still open ? Can I work on this issue ??

**Comment by Nishchit14** [comment]
@rohitmondal03 The page has already been created but not published yet.  thanks for showing your interest.
